parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''
    
services:
    mercure.hub.default:
        class: App\Tests\Functional\Stub\HubStub
        
    App\Service\SongProvider\SongProviderStub: ~
    App\Service\SongProvider\SongProviderInterface: '@App\Service\SongProvider\SongProviderStub'
